import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { formatDeckLabel, formatUsd } from '../deck-builder';
import { ColorSymbols } from './ColorSymbols';
export function DeckDashboard(props) {
    return (_jsxs("section", { className: "dashboard", children: [_jsxs("div", { className: "dashboard-header", children: [_jsxs("div", { children: [_jsx("h1", { children: "Meus Decks" }), _jsxs("p", { children: [props.decks.length, " deck(s) salvos"] })] }), _jsx("button", { onClick: props.onOpenCreate, children: "+ Novo deck" })] }), props.loadingDecks && props.decks.length === 0 ? _jsx("div", { className: "empty-panel", children: "Carregando decks..." }) : null, !props.loadingDecks && props.decks.length === 0 ? (_jsxs("div", { className: "empty-panel", children: [_jsx("h2", { children: "Seu grimorio esta vazio" }), _jsx("p", { children: "Crie seu primeiro deck para comecar a montar a colecao." }), _jsx("button", { onClick: props.onOpenCreate, children: "Criar primeiro deck" })] })) : null, _jsx("div", { className: "deck-grid", children: props.decks.map((deck) => (_jsxs("article", { className: "deck-card", children: [_jsxs("button", { className: "deck-cover", type: "button", onClick: () => props.onOpenViewer(deck.id), style: deck.coverImage
                                ? {
                                    backgroundImage: `linear-gradient(180deg, rgba(20,15,8,0.08), rgba(20,15,8,0.55)), url(${deck.coverImage})`,
                                    backgroundSize: 'cover',
                                    backgroundPosition: 'center'
                                }
                                : undefined, children: [_jsx("span", { className: "deck-badge", children: formatDeckLabel(deck.format) }), _jsx(ColorSymbols, { className: "deck-cover__colors", colors: deck.colorIdentity, size: "sm" }), _jsxs("div", { className: "deck-cover__content", children: [_jsx("strong", { children: deck.name }), _jsx("span", { children: deck.targetCards ? `${deck.totalCards}/${deck.targetCards} cartas` : `${deck.totalCards} cartas` })] })] }), _jsxs("div", { className: "deck-card__body", children: [_jsxs("div", { children: [_jsx("h3", { children: deck.name }), _jsx("p", { children: deck.commanderName || formatDeckLabel(deck.format) }), _jsx("p", { children: formatUsd(deck.estimatedPriceUsd) })] }), _jsxs("div", { className: "deck-card__actions", children: [_jsx("button", { onClick: () => props.onOpenEditor(deck.id), children: "Editar" }), _jsx("button", { className: "secondary-button", onClick: () => props.onOpenViewer(deck.id), children: "Ver" }), _jsx("button", { className: "danger-button", onClick: () => props.onDeleteDeck(deck.id), children: "Excluir" })] })] })] }, deck.id))) })] }));
}
